# Generated by Django 2.2.4 on 2021-08-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oxy', models.IntegerField()),
                ('Pulse', models.IntegerField()),
                ('Temp', models.IntegerField()),
            ],
        ),
    ]
