# Generated by Django 2.2.4 on 2021-08-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_covid_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='covid',
            new_name='CovidDb',
        ),
    ]
