# Generated by Django 2.2.4 on 2021-08-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210823_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddb',
            name='Name',
            field=models.CharField(default='kevin', max_length=100),
            preserve_default=False,
        ),
    ]
