# Generated by Django 2.2.4 on 2021-08-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_coviddb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='diabDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('glucose', models.IntegerField()),
                ('bloodpressure', models.IntegerField()),
                ('skinthickness', models.IntegerField()),
                ('bmi', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('pedigree', models.IntegerField()),
                ('age', models.IntegerField()),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
