# Generated by Django 2.2.4 on 2021-08-26 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_diabdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diabdb',
            old_name='result',
            new_name='result1',
        ),
    ]
