# Generated by Django 2.2.4 on 2021-10-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210826_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='alco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('bac_val', models.FloatField()),
            ],
        ),
    ]
