# Generated by Django 2.2.4 on 2021-10-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alco',
            old_name='Fname',
            new_name='FName',
        ),
        migrations.AddField(
            model_name='alco',
            name='result2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
