# Generated by Django 2.2.4 on 2021-10-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211006_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alco',
            old_name='FName',
            new_name='FName1',
        ),
    ]
