# Generated by Django 2.2.4 on 2021-10-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211011_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alco',
            old_name='FName1',
            new_name='namea',
        ),
    ]
