# Generated by Django 2.2.4 on 2021-10-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211011_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alco',
            old_name='namea',
            new_name='Name1',
        ),
    ]
